const refreshTokenKey = "refreshToken";
const tokenKey = "token";
const userIdKey = "userId";
const languageKey = "language";
const userNameKey = "userName";
const environmentKey="environment";
const onboardingKey = "onboarding";
const searchListKey= "searchList";
const userFirstNameKey = "userFirstName";